# Generated by Django 5.1.1 on 2024-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, default='Не указано', null=True, verbose_name='Год выпуска'),
        ),
    ]
